import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import HomePage from '@/components/HomePage'
import { useState } from 'react'
import SideNav from '@/components/SideNav'
const inter = Inter({ subsets: ['latin'] })
import { motion,AnimatePresence } from 'framer-motion'

export default function Home() {
  const [sideNav,setSideNav]= useState(true)

  const sidebarHandler = () => {
    // setSideNav(!sideNav)
    console.log('nave')
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.main    className=''>
  

      <AnimatePresence>

      <motion.div  
        // animate={{ transform: "translateX(100px)" }}
      // initial={{ opacity: 0.6 }}
  // whileHover={{
  //   scale: 1.2,
  //   transition: { duration: 1 },
  // }}
  // whileTap={{ scale: 0.9 }}
  // whileInView={{ opacity: 1 }}
   className={sideNav?('grid grid-cols-5'):""}>
            {
              sideNav?( 
             <SideNav/>):null 
            }
         

            <div className=' col-start-2 col-end-6'> 
            <Navbar sideNav={setSideNav} status={sideNav}></Navbar>
           <HomePage/>
           </div>
        </motion.div>
</AnimatePresence>
       
       
       
      </motion.main>
    </>
  )
}
